core/urls.py
from django.urls import path
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    SearchResultsView1,
    SearchResultsView2,
    SearchResultsView3,
    SearchResultsView4,
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('products_by_pharmacy_1/', SearchResultsView1.as_view(), name='products_by_pharmacy_1'),
    path('products_by_pharmacy_2/', SearchResultsView2.as_view(), name='products_by_pharmacy_2'),
    path('products_by_pharmacy_3/', SearchResultsView3.as_view(), name='products_by_pharmacy_3'),
    path('products_by_pharmacy_4/', SearchResultsView4.as_view(), name='products_by_pharmacy_4'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


CATEGORY_CHOICES = (
    ('N', 'Nahdi'),
    ('D', 'Dawaa'),
    ('W', 'Whites'),
    ('K', 'Kunooz'),
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/Al-dawaa.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<main>
    <div class="row col-md-12 text-center p-4 mt-4">
        <div class="col-md-8 offset-2">
            <div class="content">
                <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">

                    <!-- Navbar brand -->
                    <span class="navbar-brand">Search In Al-dawaa Pharmacy:</span>
                    <!-- Collapse button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Collapsible content -->
                    <ul class="navbar-nav mr-5 ml-5">
                    </ul>
                    <div class="collapse navbar-collapse" id="basicExampleNav">
                        <form class="form-inline">
                            <div class="md-form my-0">
                                <input onkeyup="myFunction()" id="myInput" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                            </div>
                        </form>
                    </div>
                    <!-- Collapsible content -->

                </nav>
            </div>
        </div>
    </div>
    <!-- carousel -->
    <div class="container">

        <!--Navbar-->
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn" id="MainClass">

                {% for item in object_list %}
                <div class="col-lg-3 col-md-6 mb-4 subClass">

                    <div class="card">

                        <div class="view overlay">
                            {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                            <img style="height: 200px" src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a href="" class="grey-text"><h5>{{ item.get_category_display }}</h5></a>
                            <h5>
                                <strong>
                                    <a id="searchrr" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                        <span class="badge badge-pill {{ item.get_label_display }}-color"></span>
                                    </a>
                                </strong>
                            </h5>

                            <h4 class="font-weight-bold blue-text">
                                <strong>SAR
                                    {% if item.discount_price %}
                                    {{ item.discount_price }}
                                    {% else %}
                                    {{ item.price }}
                                    {% endif %}
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
    </div>
</main>

{% endblock content %}

templates/Kunooz.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<main>
    <div class="row col-md-12 text-center p-4 mt-4">
        <div class="col-md-8 offset-2">
            <div class="content">
                <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">

                    <!-- Navbar brand -->
                    <span class="navbar-brand">Search In Kunooz Pharmacy:</span>
                    <!-- Collapse button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Collapsible content -->
                    <ul class="navbar-nav mr-5 ml-5">
                    </ul>
                    <div class="collapse navbar-collapse" id="basicExampleNav">
                        <form class="form-inline">
                            <div class="md-form my-0">
                                <input onkeyup="myFunction()" id="myInput" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                            </div>
                        </form>
                    </div>
                    <!-- Collapsible content -->

                </nav>
            </div>
        </div>
    </div>
    <!-- carousel -->
    <div class="container">

        <!--Navbar-->
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn" id="MainClass">

                {% for item in object_list %}
                <div class="col-lg-3 col-md-6 mb-4 subClass">

                    <div class="card">

                        <div class="view overlay">
                            {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                            <img style="height: 200px" src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a href="" class="grey-text"><h5>{{ item.get_category_display }}</h5></a>
                            <h5>
                                <strong>
                                    <a id="searchrr" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                        <span class="badge badge-pill {{ item.get_label_display }}-color"></span>
                                    </a>
                                </strong>
                            </h5>

                            <h4 class="font-weight-bold blue-text">
                                <strong>SAR
                                    {% if item.discount_price %}
                                    {{ item.discount_price }}
                                    {% else %}
                                    {{ item.price }}
                                    {% endif %}
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
    </div>
</main>

{% endblock content %}

templates/Whites.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<main>
    <div class="row col-md-12 text-center p-4 mt-4">
        <div class="col-md-8 offset-2">
            <div class="content">
                <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-5 mb-5">

                    <!-- Navbar brand -->
                    <span class="navbar-brand">Search In Whites Pharmacy:</span>
                    <!-- Collapse button -->
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                            aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Collapsible content -->
                    <ul class="navbar-nav mr-5 ml-5">
                    </ul>
                    <div class="collapse navbar-collapse" id="basicExampleNav">
                        <form class="form-inline">
                            <div class="md-form my-0">
                                <input onkeyup="myFunction()" id="myInput" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                            </div>
                        </form>
                    </div>
                    <!-- Collapsible content -->

                </nav>
            </div>
        </div>
    </div>
    <!-- carousel -->
    <div class="container">

        <!--Navbar-->
        <!--/.Navbar-->

        <!--Section: Products v.3-->
        <section class="text-center mb-4">

            <div class="row wow fadeIn" id="MainClass">

                {% for item in object_list %}
                <div class="col-lg-3 col-md-6 mb-4 subClass">

                    <div class="card">

                        <div class="view overlay">
                            {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                            <img style="height: 200px" src="{{ item.image.url }}" class="card-img-top">
                            <a href="{{ item.get_absolute_url }}">
                                <div class="mask rgba-white-slight"></div>
                            </a>
                        </div>

                        <div class="card-body text-center">
                            <a href="" class="grey-text"><h5>{{ item.get_category_display }}</h5></a>
                            <h5>
                                <strong>
                                    <a id="searchrr" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                                        <span class="badge badge-pill {{ item.get_label_display }}-color"></span>
                                    </a>
                                </strong>
                            </h5>

                            <h4 class="font-weight-bold blue-text">
                                <strong>SAR
                                    {% if item.discount_price %}
                                    {{ item.discount_price }}
                                    {% else %}
                                    {{ item.price }}
                                    {% endif %}
                                </strong>
                            </h4>

                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>

        </section>
    </div>
</main>

{% endblock content %}

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <!--Copyright-->
    <div class="footer-copyright py-3">
<!--      © 2023 Copyright:-->
<!--      <a href="#" target="_blank">Develop By : Dalal Mohammed</a>-->
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}


  <main>
    <div class="row col-md-12 text-center p-4 mt-4">
      <div class="col-md-3">
        <div class="content">
          <img src="{% static 'img/a.jpeg' %}" class="imageContent">
          <p>Nahdi</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="content">
          <img src="{% static 'img/al.jpeg' %}" class="imageContent">
          <p>Al-dawaa</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="content">
          <img src="{% static 'img/w.jpeg' %}" class="imageContent">
          <p>Whites</p>
        </div>
      </div>
      <div class="col-md-3">
        <div class="content">
          <img src="{% static 'img/k.jpeg' %}" class="imageContent">
          <p>Kunooz</p>
        </div>
      </div>
    </div>
    <!-- carousel -->
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Pharmacies:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:products_by_pharmacy_1' %}?q=N">Nahdi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:products_by_pharmacy_2' %}?q=D">Al-dawaa</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:products_by_pharmacy_3' %}?q=W">Whites</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:products_by_pharmacy_4' %}?q=K">Kunooz</a>
            </li>

          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input onkeyup="myFunction()" id="myInput" class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <section class="text-center mb-4">

        <div class="row wow fadeIn" id="MainClass">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4 subClass">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img style="height: 200px" src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text"><h5>{{ item.get_category_display }}</h5></a>
                <h5>
                  <strong>
                    <a id="searchrr" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                    <span class="badge badge-pill {{ item.get_label_display }}-color"></span>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>SAR
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>


      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <img src="{% static 'img/logo.png' %}"     height="61px">
        <strong class="title">Products World</strong>
      </a>
      <ul class="navbar-nav me-auto ml-5 mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " href="/">Home</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="product.html">Products</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="login.html">Login</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="register.html">Register</a>-->
<!--        </li>-->
      </ul>
      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          {% comment %} <li class="nav-item active">
            <a class="nav-link waves-effect" href="/">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="/checkout">
            Checkout</a>
          </li> {% endcomment %}
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main class="mt-5 pt-4 mb-5 pb-5">
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Shopping Cart</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>
            <td>{{ order_item.item.price }}</td>
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
            {% if order_item.item.discount_price %}
                SAR {{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving SAR {{ order_item.get_amount_saved }}</span>
            {% else %}
                SAR {{ order_item.get_total_item_price }}
            {% endif %}
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endfor %}
        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-SAR {{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        {% if object.get_total %}
        <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>SAR {{ object.get_total }}</b></td>
        </tr>
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image.url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>SAR {{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>SAR {{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4"></h4>

          <p></p>

        </div>
        <!--Grid column-->

      </div>

    </div>
  </main>

{% endblock content %}